scalar Upload

type Dataset {
  id: ID!
  name: String!
  description: String
  s3Key: String!
  sizeBytes: Int
  rowCount: Int
  createdAt: String!
  updatedAt: String!
  fileUrl: String
}

input CreateDatasetInput {
  name: String!
  description: String
}

input UpdateDatasetInput {
  name: String
  description: String
}

extend type Query {
  datasets: [Dataset!]!
  dataset(id: ID!): Dataset!
  datasetHeaders(id: ID!): [String!]!
}

extend type Mutation {
  createDataset(input: CreateDatasetInput!, file: Upload!): Dataset!
  updateDataset(id: ID!, input: UpdateDatasetInput!): Dataset!
  deleteDataset(id: ID!): Boolean!
}
