scalar JSON

enum GraphStatus {
  PROCESSING
  READY
  FAILED
}

type Graph {
  id: Int!
  name: String!
  status: GraphStatus!
  isDirected: Boolean!
  isWeighted: Boolean!
  nodeCount: Int
  edgeCount: Int
  density: Float
  componentsCount: Int
  communitiesCount: Int
  shareSlug: String
  graphData: JSON
  createdAt: String!
  updatedAt: String!
  dataset: Dataset!
}

input CreateGraphInput {
  name: String!
  datasetId: Int!
  isDirected: Boolean
  isWeighted: Boolean
}

input UpdateGraphInput {
  name: String
  status: GraphStatus
  isDirected: Boolean
  isWeighted: Boolean
  shareSlug: String
}

extend type Query {
  graphs: [Graph!]!
  graph(id: Int!): Graph!
}

extend type Mutation {
  createGraph(input: CreateGraphInput!): Graph!
  regenerateGraph(id: Int!): Graph!
  updateGraph(id: Int!, input: UpdateGraphInput!): Graph!
  deleteGraph(id: Int!): Boolean!
}
